### ISSUE TITLE
Possibilty to shop popup to confirm delete

### ISSUE THREAD

**Issue by JelleGe** [yireo/Yireo_DeleteAnyOrder2#1]
Hi,

Is there a way to show a popup, to confirm that you are sure to delete the order?
Now it directly delete the order.

This additional step is to be sure that you delete only the right orders.

**Comment by jissereitsma** [comment]
Done. https://github.com/yireo/Yireo_DeleteAnyOrder2/commit/94f6756c08be88939031d667e15c418b66c0964f
